ext/fileinfo/libmagic/apprentice.lo: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/fileinfo/data_file.c
/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_scanner.c /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/php_json_scanner_defs.h: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_scanner.re /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_parser.tab.h
	@$(RE2C) $(RE2C_FLAGS) -t /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/php_json_scanner_defs.h --no-generation-date -bci -o /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_scanner.c /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_scanner.re

/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_parser.tab.c /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_parser.tab.h: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_parser.y
	@$(YACC) $(YFLAGS) --defines -l /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_parser.y -o /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/json/json_parser.tab.c
phpincludedir=$(prefix)/include/php

PDO_HEADER_FILES= \
	php_pdo.h \
	php_pdo_driver.h \
	php_pdo_error.h


/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/pdo/pdo_sql_parser.c: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/pdo/pdo_sql_parser.re
	@(cd $(top_srcdir); \
	if test -f ./pdo_sql_parser.re; then \
		$(RE2C) $(RE2C_FLAGS) --no-generation-date -o pdo_sql_parser.c pdo_sql_parser.re; \
	else \
		$(RE2C) $(RE2C_FLAGS) --no-generation-date -o ext/pdo/pdo_sql_parser.c ext/pdo/pdo_sql_parser.re; \
	fi)

install-pdo-headers:
	@echo "Installing PDO headers:           $(INSTALL_ROOT)$(phpincludedir)/ext/pdo/"
	@$(mkinstalldirs) $(INSTALL_ROOT)$(phpincludedir)/ext/pdo
	@for f in $(PDO_HEADER_FILES); do \
		if test -f "$(top_srcdir)/$$f"; then \
			$(INSTALL_DATA) $(top_srcdir)/$$f $(INSTALL_ROOT)$(phpincludedir)/ext/pdo; \
		elif test -f "$(top_builddir)/$$f"; then \
			$(INSTALL_DATA) $(top_builddir)/$$f $(INSTALL_ROOT)$(phpincludedir)/ext/pdo; \
		elif test -f "$(top_srcdir)/ext/pdo/$$f"; then \
			$(INSTALL_DATA) $(top_srcdir)/ext/pdo/$$f $(INSTALL_ROOT)$(phpincludedir)/ext/pdo; \
		elif test -f "$(top_builddir)/ext/pdo/$$f"; then \
			$(INSTALL_DATA) $(top_builddir)/ext/pdo/$$f $(INSTALL_ROOT)$(phpincludedir)/ext/pdo; \
		else \
			echo "hmmm"; \
		fi \
	done;

# mini hack
install: $(all_targets) $(install_targets) install-pdo-headers
/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/standard/var_unserializer.c: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/standard/var_unserializer.re
	@(cd $(top_srcdir); $(RE2C) $(RE2C_FLAGS) --no-generation-date -b -o ext/standard/var_unserializer.c ext/standard/var_unserializer.re)

/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/standard/url_scanner_ex.c: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/standard/url_scanner_ex.re
	@(cd $(top_srcdir); $(RE2C) $(RE2C_FLAGS) --no-generation-date -b -o ext/standard/url_scanner_ex.c	ext/standard/url_scanner_ex.re)

ext/standard/info.lo: ext/standard/../../main/build-defs.h

ext/standard/basic_functions.lo: $(top_srcdir)/Zend/zend_language_parser.h
$(top_srcdir)/ext/tokenizer/tokenizer_data.c: $(top_srcdir)/Zend/zend_language_parser.y
	@if test ! -z "$(PHP)"; then \
		$(PHP) /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/ext/tokenizer/tokenizer_data_gen.php; \
	fi;
ext/tokenizer/tokenizer.lo: $(top_srcdir)/Zend/zend_language_parser.c $(top_srcdir)/Zend/zend_language_scanner.c
#
# Build environment install
#

phpincludedir = $(includedir)/php
phpbuilddir = $(libdir)/build

BUILD_FILES = \
	scripts/phpize.m4 \
	build/libtool.m4 \
	build/ltmain.sh \
	build/ax_check_compile_flag.m4 \
	build/ax_gcc_func_attribute.m4 \
	build/php_cxx_compile_stdcxx.m4 \
	build/pkg.m4 \
	build/Makefile.global \
	build/php.m4 \
	build/gen_stub.php \
	run-tests.php

BUILD_FILES_EXEC = \
	build/shtool \
	build/config.guess \
	build/config.sub

bin_SCRIPTS = phpize php-config
man_PAGES = phpize php-config

install-build:
	@echo "Installing build environment:     $(INSTALL_ROOT)$(phpbuilddir)/"
	@$(mkinstalldirs) $(INSTALL_ROOT)$(phpbuilddir) $(INSTALL_ROOT)$(bindir) && \
	(cd $(top_srcdir) && \
	$(INSTALL) $(BUILD_FILES_EXEC) $(INSTALL_ROOT)$(phpbuilddir) && \
	$(INSTALL_DATA) $(BUILD_FILES) $(INSTALL_ROOT)$(phpbuilddir))

install-programs: scripts/phpize scripts/php-config
	@echo "Installing helper programs:       $(INSTALL_ROOT)$(bindir)/"
	@$(mkinstalldirs) $(INSTALL_ROOT)$(bindir)
	@for prog in $(bin_SCRIPTS); do \
		echo "  program: $(program_prefix)$${prog}$(program_suffix)"; \
		$(INSTALL) -m 755 scripts/$${prog} $(INSTALL_ROOT)$(bindir)/$(program_prefix)$${prog}$(program_suffix); \
	done
	@echo "Installing man pages:             $(INSTALL_ROOT)$(mandir)/man1/"
	@$(mkinstalldirs) $(INSTALL_ROOT)$(mandir)/man1
	@for page in $(man_PAGES); do \
		echo "  page: $(program_prefix)$${page}$(program_suffix).1"; \
		$(INSTALL_DATA) scripts/man1/$${page}.1 $(INSTALL_ROOT)$(mandir)/man1/$(program_prefix)$${page}$(program_suffix).1; \
	done

scripts/phpize: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/scripts/phpize.in $(top_builddir)/config.status
	(CONFIG_FILES=$@ CONFIG_HEADERS= $(top_builddir)/config.status)

scripts/php-config: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/scripts/php-config.in $(top_builddir)/config.status
	(CONFIG_FILES=$@ CONFIG_HEADERS= $(top_builddir)/config.status)
#
# Zend
#

Zend/zend_language_scanner.lo: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.h
Zend/zend_ini_scanner.lo: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_parser.h

/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_scanner.c /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_scanner_defs.h: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_scanner.l
	@(cd $(top_srcdir); $(RE2C) $(RE2C_FLAGS) --no-generation-date --case-inverted -cbdFt Zend/zend_language_scanner_defs.h -oZend/zend_language_scanner.c Zend/zend_language_scanner.l)

/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.h: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.c
/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.c: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.y
# Tweak zendparse to be exported through ZEND_API. This has to be revisited once
# bison supports foreign skeletons and that bison version is used. Read
# https://git.savannah.gnu.org/cgit/bison.git/tree/data/README.md for more.
	@$(YACC) $(YFLAGS) -v -d /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.y -o $@
	@$(SED) -e 's,^int zendparse\(.*\),ZEND_API int zendparse\1,g' < $@ \
	> $@.tmp && \
	mv $@.tmp $@
	@$(SED) -e 's,^int zendparse\(.*\),ZEND_API int zendparse\1,g' < /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.h \
	> /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.h.tmp && \
	mv /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.h.tmp /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.h

/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_parser.h: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_parser.c
/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_parser.c: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_parser.y
	$(YACC) $(YFLAGS) -v -d /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_parser.y -o $@

/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_scanner.c: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_ini_scanner.l
	@(cd $(top_srcdir); $(RE2C) $(RE2C_FLAGS) --no-generation-date --case-inverted -cbdFt Zend/zend_ini_scanner_defs.h -oZend/zend_ini_scanner.c Zend/zend_ini_scanner.l)

# Use an intermediate target to indicate that zend_vm_gen.php produces both files
# at the same time, rather than the same recipe applying for two different targets.
# The "grouped targets" feature, which would solve this directly, is only available
# since GNU Make 4.3.
/Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_execute.h /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_opcodes.c: vm.gen.intermediate ;
.INTERMEDIATE: vm.gen.intermediate
vm.gen.intermediate: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_def.h /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_execute.skl /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_gen.php
	@if test ! -z "$(PHP)"; then \
		$(PHP) /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_gen.php; \
	fi;

Zend/zend_highlight.lo Zend/zend_compile.lo: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_language_parser.h

Zend/zend_execute.lo: /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_execute.h /Users/noguchi/Desktop/nativephp-mobile-mysql-template/mobile-libphp-builder/ios-build/php-8.3.30/Zend/zend_vm_opcodes.h
